### ISSUE TITLE
Does/Can this work with enum values?

### ISSUE THREAD

**Issue by bzbetty** [yv989c/BlazarTech.QueryableValues#23]
I notice there's no overloads specifically for them, so i tried the generic overload

> public static IQueryable<TSource> AsQueryableValues<TSource>(this DbContext dbContext, IEnumerable<TSource> values, Action<EntityOptionsBuilder<TSource>>? configure = null) where TSource : notnull

but that resulted in an exception.

Is this a supported scenario already?

**Comment by bzbetty** [comment]
seems that casting the enum to a primitive works, bit ugly but it works

> ctx.AsQueryableValues(args.jobTypes!.Cast<int>()).Contains((int)i.TypeId)

**Comment by yv989c** [comment]
Hi! I'll close the issue now. If there's anything else feel free to open a new one.

Thanks.
