### ISSUE TITLE
Enum Support

### ISSUE THREAD

**Issue by OculiViridi** [yv989c/BlazarTech.QueryableValues#33]
I've a service that builds a dynamic query `WHERE` condition based on some filters.
I'm trying to use your library to build one of those filter, related to an array of enum values, but I'm getting this Exception at runtime:

> The type `MyProject.Api.Data.Models.OperationType` must have at least one public property.

The user can select one or more of those values and so the `WHERE` condition has to be built using `OR`.

The `MyProject.Api.Data.Models.OperationType` is an enum type defined as follows:

```csharp
public enum OperationType : byte
{
    DT = 1,
    NP = 2,
    Tx = 3,
    RE = 4,
    I = 5,
    AT = 6,
    M = 7,
    TR = 8,
    TxAT = 9
}
```

My actual code for building the query is this:

```csharp
...
if (filter.OperationTypes?.Any() == true)
{
    // Conversion from API enum model to EF enum model
    var operationTypes = filter.OperationTypes.Select(c => Enum.Parse<Data.Models.OperationType>(c.ToString(), true)).ToArray();
	
    // Call to AsQueryableValues that causes the Exception
    var queryableValues = _dbContext.AsQueryableValues(operationTypes);

    query = query.Where(x => x.Movements.OperationType != null && queryableValues.Contains(x.Movements.OperationType.Value));
}
...
```

Am I doing something wrong? How am I supposed to use the library with enums?

**Comment by yv989c** [comment]
Hi @OculiViridi , unfortunately the library doesn't support this use case at the moment; it supports the following [simple types](https://github.com/yv989c/BlazarTech.QueryableValues#simple-type-examples) or [complex types](https://github.com/yv989c/BlazarTech.QueryableValues#complex-type-example).

Having said that, what if you project your enum as its underlying data type –assuming `byte` per your stub– and use that instead? like this:
```c#
...
if (filter.OperationTypes?.Any() == true)
{
    // Conversion from API enum model to EF enum model
    // *** Notice the cast to byte ***
    var operationTypes = filter.OperationTypes.Select(c => Enum.Parse<Data.Models.OperationType>(c.ToString(), true)).Select(i => (byte)i);
	
    // Call to AsQueryableValues that causes the Exception
    var queryableValues = _dbContext.AsQueryableValues(operationTypes);

    // *** Notice the cast to byte ***
    query = query.Where(x => x.Movements.OperationType != null && queryableValues.Contains((byte)x.Movements.OperationType.Value));
}
...
```
If `byte` doesn't work, try with `int`.

**Comment by OculiViridi** [comment]
> If `byte` doesn't work, try with `int`.

Seems to work fine both with `byte` and with `int`.

**Comment by yv989c** [comment]
### Tasks
- [X] `IEnumerable<Enum>`
- [ ] `Enum` property in complex type (`IEnumerable<ComplexType>`)
- [ ] Update docs
